GET http://localhost:3000/

###

POST http://localhost:3000/
Content-Type: application/json

{
    "title": "Eloquent JavaScript, Second Edition",
    "author": "Marijn Haverbeke",
    "publisher": "No Starch Press",
    "numOfPages": 472
}

###

DELETE http://localhost:3000/2

###

Put http://localhost:3000/1
Content-Type: application/json

{
    "title": "test",
    "author": "Marijn Haverbeke",
    "publisher": "No Starch Press",
    "numOfPages": 472
}