GET localhost:3000

###

POST http://localhost:3000/book
Content-Type: application/json

{
    "isbn": 9781593275846,
    "title": "Eloquent JavaScript, Second Edition",
    "author": "Marijn Haverbeke",
    "publish_date": "2014-12-14",
    "publisher": "No Starch Press",
    "numOfPages": 472
}
